### ISSUE TITLE
derive(Display) does not propagate the alternate flag

### ISSUE THREAD

**Issue by troiganto** [JelteF/derive_more#107]
In some of my code, I've been using the alternate flag `{:#}` to modify some formatting. I've been relying on the fact that deriving Display on an enum would propagate this flag downwards. (same for Binary, Octal, LowerHex, UpperHex, LowerExp, UpperExp, Pointer)

However, sometime betwee versions 0.15.0 and 0.99.1, this seems to have changed. (A quick bisect has led me to the commit d8de4b80.)

Minimal reproduction:
```rust
use derive_more::{Display, Binary, Octal};

#[derive(Display, Binary, Octal)]
struct MyInt(u32);

#[test]
fn check_display() {
    assert_eq!(format!("{:b}", MyInt(9)), "1001");
    assert_eq!(format!("{:#b}", MyInt(9)), "0b1001");
}
```
Using the current master, the second line currently fails because `MyInt(9)` gets formatted as "1001" instead.

Has this change been made on purpose? If not, what would be the best way to solve this issue? I don't have a lot of experience with proc-macros, but I'm sure with a few pointers, I could put together a PR.

**Comment by JelteF** [comment]
That's definitely an unintended side effect of that commit. One thing that
definitely helps in fixing things like this is if you modify the currently
generated code to to create the intended effect.

You can get the currently generated using cargo expand (for Display derives
it might not be great though, since write! is also a macro and will thus be
expanded as well). The reason for this is that generating the correct code
is much easier once you know what the correct code actually is.
