### ISSUE TITLE
make derive From more useful

### ISSUE THREAD

**Issue by xoac** [JelteF/derive_more#119]
Hi guys

Minimal concept example
```rust
#[derive(From)]
enum MyEnum {
   #[from(i8,u8,i16,u16,i32,u32,i64)]
   Number(i64)
}
```

This would generate `From` trait for every type that can be converted to `i64` and it is listed in `from` attribute. 

What do you think?

**Comment by JelteF** [comment]
What's the reason you would use this over the #[from(forward)] attribute?

**Comment by xoac** [comment]
Oh I just read about use-case on enum. Sorry I missed it in doc but it's still useless in my case. 

Answering your question - this allow you to specify exactly what type you want to convert from. 

#[derive(From)]
```rust
enum Number {
  #[from(i8, i16, i32, i64)]
  Signed(i64)
  #[from(forward)] // this will not conflict with upper and bellow
  Unsigned(u64)
  // I don't wanna convert from integers just from floats
  #[from(f32, f64)]
  Float(f64)
}
```

The second reason is `forward` make it a bit out of control since you can't say from what types it will be generated (sometimes it's not what you want).

**Comment by JelteF** [comment]
Hmm, yeah that's actually a good use case for this indeed. Feel free to make a PR for this implementing it. To make it more easy to stay backwards compatible though, please use the following syntax:
```
#[from(types(i8, i16, i32, i64))]
```

**Comment by xoac** [comment]
I have tried to jump into code but it's a little bit complicated to me. I have just once worked with creating derive. Could you give me some general insight where I should start? It would be also helpful to add some doc-comments in `utils` module. Is there a way to chat with you if I would have concerns? 

Did you think about spiting this crate to sup-crates and then just reexport them I think people mostly are looking just for a single costume derive?:
- not all derive require so complicated utils to be implemented (and utils could be also be useful separate crate - not only for this project)
- it would be easier findable (in `Cargo.toml` you can specify only  5 [keywords](https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field))
- you would have probably more contributors

**Comment by JelteF** [comment]
The code is indeed not the most clear and comments are quite lacking in most places. The way I would recommend starting with this is
1. create a separate test file, e.g. tests/from_types.rs.
2. Put in the syntax you want there
3. Use `cargo expand --test from_types` to see what comes out
4. Modify `from.rs` and `utils.rs` to make it output what you want
5. Repeat 3 and 4 until you have what you want.

In `utils.rs` the main thing you probably need to change are:
1. In utils, add support for parsing the `types` subattribute in `parse_punctuated_nested_meta`
2. In `from.rs` create in impl for each element in `types` for `struct_from`, instead of just a single one
3. Other than that you should use the `State` struct from `utils.rs` and it's related methods. Most methods defined above the `State` struct in the `utils.rs` file are old and not useful for new code.
