### ISSUE TITLE
Support trait objects for source in Error

### ISSUE THREAD

**Issue by alexbool** [JelteF/derive_more#122]
Currently you can't just write
```rust
#[derive(Debug, Display, Error)]
pub enum MyError {
    #[display(fmt = "something failed")]
    Failed {
        #[error(source)]
        source: Box<dyn Error + Send + 'static>,
    },
   ...
}
```

This is what compiler says:
```
100 | #[derive(Debug, Display, Error)]
    |                          ^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `(dyn std::error::Error + std::marker::Send + 'static)`
```

BTW `thiserror` supports this pattern.

**Comment by JelteF** [comment]
Turns out `thiserror` does it using this way: https://github.com/dtolnay/thiserror/blob/master/src/aserror.rs

Which means that to replicate the same runtime support is needed in `derive_more`. Which will mean some restructuring of the crate layout. Which means have to figure out how to do that correctly while still supporting `no_std`.

**Comment by JelteF** [comment]
@ilslv @tyranron I feel like now that we have the new two-crate layout, this should be really easy to copy from thiserror. Correctly doing the license attribution is probably the most work.

**Comment by JelteF** [comment]
Re-opening because I reverted the commit that closed it because I accidentally pushed it straight to master
