### ISSUE TITLE
backtrace method was removed by Rust

### ISSUE THREAD

**Issue by JelteF** [JelteF/derive_more#195]
@tyranron @ilslv The tests started failing with the most recent rust nightlies because of this: https://github.com/rust-lang/rust/pull/99431

Could you spend some time to fix it and use the Provider API instead? https://github.com/rust-lang/rust/issues/96024

I wanted to release version 1.0.0 of derive_more but this blocks me from doing that.

**Comment by tyranron** [comment]
cc @ilslv 

@JelteF will do in a couple of days.

**Comment by JelteF** [comment]
If it's hard to get the provider API working, e.g. because it's not ready yet. Then I think we can temporarily remove backtrace functionality from derive_more until we can create a good implementation.

**Comment by tyranron** [comment]
@JelteF btw, would you consider to release `0.100.0` version instead of `1.0.0`. I think there are more breaking things to be done before going `1.0.0`. The main of them is making this crate consisting of two: `derive_more_codegen` containing proc macro implementations + `derive_more` non-`procmacro` crate re-exporting macros from `derive_more_codegen` and providing some type-level glue to aid those macros in their expansion. Such type level glue may improve macro ergonomics and cleverness. One of such cases is [this one](https://github.com/JelteF/derive_more/issues/122#issuecomment-609019071).

**Comment by JelteF** [comment]
Maybe I'm missing something, but a quick look at thiserror suggests that shouldn't be a breaking change. Th `derive_more` non-procmacro crate can simply re-export the derives like this: https://github.com/dtolnay/thiserror/blob/master/src/lib.rs#L214

**Comment by tyranron** [comment]
@JelteF makes sense. Even changes like `#[display(fmt = "{}", "expression.to.execute()")]` -> `#[display(fmt = "{}", expression.to.execute())]` (using tokens directly instead of stringifying them) we still may do in backward-compatible manner, allowing both cases until the next major release. Then OK.

**Comment by ilslv** [comment]
@JelteF @tyranron I'm not really sure, how to make transition to `Provider` API here. Basically now we have [`provide()`](https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.provide) method instead of the `backtrace()`, which uses [`Demand`](https://doc.rust-lang.org/nightly/std/any/struct.Demand.html) to provide some "context". As this API is quite new and there is no practice of using it inside the Rust's ecosystem, I'm not really sure how to approach it: 

```rust
enum MyError {
    First(FirstError),
    Second { source: SecondError, backtrace: Backtrace }
}

impl Error for MyError {
    fn provide<'a>(&'a self, demand: &mut Demand<'a>) {
        match self {
            First(first) => {
                // What should we do here?
                // 1. Just try to call provide on `first`?
                first.provide(demand);
                // 2. Attach it as a concrete type?
                demand.provide_ref::<FirstError>(first);
                // 3. Attach it as `dyn Error`?
                demand.provide_ref::<dyn Error>(first);
                // Or all 3 of them?
            }
            Second { source, backtrace } => {
                // All questions above are still valid for `source`.
                // But with `backtrace`, it's clear to me, that we should
                // attach it.
                demand.provide_ref::<Backtrace>(backtrace);
            }
        }
    }
}
``` 

I propose to wait until there is more understanding of `Provider` API role in Rust's error handling ecosystem. Especially when new approaches that leverage `Provider` are surfacing, like [`error-stack`](https://docs.rs/error-stack/latest/error_stack/).  And until then we can just remove `backtrace()` impls. 

`thiserror` has [this issue](https://github.com/dtolnay/thiserror/issues/177) too.

**Comment by tyranron** [comment]
> Then I think we can temporarily remove backtrace functionality from derive_more until we can create a good implementation.

@ilslv ☝️

**Comment by ilslv** [comment]
@tyranron It looks like `thiserror` fixed this issue: https://github.com/dtolnay/thiserror/pull/182

```rust
enum MyError {
    First(#[error(source)] FirstError),
    Second { #[error(source)] source: SecondError, #[error(backtrace)] backtrace: Backtrace }
}

impl Error for MyError {
    fn provide<'a>(&'a self, demand: &mut Demand<'a>) {
        match self {
            First(first) => {
                first.provide(demand);
            }
            Second { source, backtrace } => {
                source.provide(demand);
                demand.provide_ref::<Backtrace>(backtrace);
            }
        }
    }
}
```

I think it looks reasonable and we should mirror the implementation.

**Comment by tyranron** [comment]
@ilslv 👍
