### ISSUE TITLE
Wait for Rust 1.65 for our 1.0 release

### ISSUE THREAD

**Issue by JelteF** [JelteF/derive_more#202]
The 1.0 release is pretty much ready from our side. So I was planning to release it in the next few days. But after reading up on the `let_else` Rust feature, I learned that this will be stabilized in Rust 1.65, which is early November.

Personally I think this feature can make the code base much more readable. So, I'm now planning to wait for the 1.65 release and set our MSRV to 1.65 for derive_more 1.0.

@tyranron does that sound good to you?

**Comment by phip1611** [comment]
Hey! In https://github.com/JelteF/derive_more/pull/192#issuecomment-1152091758 @tyranron said that you should add `#[automatically_derived]` to several places. Seems like this didn't happen yet. Any comment?

**Comment by tyranron** [comment]
@JelteF yes. Sounds, good to me.

@phip1611 yup, there was an issue disallowing merging PRs properly due to CI. Now it's resolved, so we'll cover the things shortly.

> PS: I just found this. https://github.com/JelteF/derive_more/blob/master/Cargo.toml#L71 you might want to change that (at least the comment) as well, as the MSRV is bumped?

Thanks, will take a look into.

**Comment by tyranron** [comment]
@phip1611 

> Hey! In [#192 (comment)](https://github.com/JelteF/derive_more/pull/192#issuecomment-1152091758) @tyranron said that you should add `#[automatically_derived]` to several places. Seems like this didn't happen yet. Any comment?

Done in https://github.com/JelteF/derive_more/pull/203.

**Comment by tyranron** [comment]
@phip1611 

> PS: I just found this. https://github.com/JelteF/derive_more/blob/master/Cargo.toml#L71 you might want to change that (at least the comment) as well, as the MSRV is bumped?

Done in https://github.com/JelteF/derive_more/pull/204.

**Comment by tyranron** [comment]
@JelteF before going 1.0 I would like to propose more breaking changes.

## 1. Rename `CustomDebug` as `DebugCustom` (or even `DebugSmart`)

I would like in future to add more derives which overlap with the ones from `std`. For example, `#[derive(Clone)]` from `std` is very stupid when it comes to generics, because it's blindly pastes `: Clone` trait bound on types parameters rather than field types, thus leads to [tones of squatting](https://github.com/cucumber-rs/cucumber/blob/da1adca9724fa504f2f56d98ad63561bb779f940/src/writer/normalize.rs#L53-L62). We already have `CustomDebug` which overlaps with `#[derive(Debug)]` and cannot be named `Debug` because of implicit `prelude` import. 

Usually, we have a code style rule to sort any enumerations in alphabetical order, so the proposed naming change is to omit any possible moves in a list of derived traits when we go from `Debug` to `CustomDebug`, but rather to add a suffix in-place to the standard derive:
- Instead of this:   
   `#[derive(AsRef, Clone, Copy, Debug, Default, Display, Eq, Error, From, PartialEq)]` -> `#[derive(AsRef, CustomClone, CustomCopy, CustomDebug, CustomDefault, CustomEq, CustomPartialEq, Display, Error, From)]`
- Have this:
  `#[derive(AsRef, Clone, Copy, Debug, Display, Eq, Error, From, PartialEq)]` -> `#[derive(AsRef, CloneCustom, CopyCustom, DebugCustom, DefaultCustom, Display, EqCustom, Error, From, PartialEqCustom)]`

I would also consider some simpler/shorter suffix rather than `Custom`, but cannot invent any good candidate at the moment rather than `Smart` (which is not ideal, btw).

`#[derive(AsRef, CloneSmart, CopySmart, DebugSmart, DefaultSmart, Display, EqSmart, Error, From, PartialEqSmart)]`

## 2. Switch to raw tokens wherever is possible

As `derive_more` had existed before arbitrary tokens became allowed in proc macro attributes, we do have places in our APIs where we overcome that limitation by wrapping code tokens into a string.

So, instead:
```rust
#[derive(Display)]
#[display(bound = "T: MyTrait, U: Display, V: Display")]
#[display(fmt = "{} {} {}", "a.my_function()", "b.to_string().len()", "c")]
struct MyStruct<T, U, V> {
    a: T,
    b: U,
    c: V,
}
```
I would like to see something like this in a modern Rust:
```rust
#[derive(Display)]
#[display(bound = T: MyTrait, U: Display, V: Display)] // or #[display(bound(T: MyTrait, U: Display, V: Display))]
#[display(fmt = "{} {} {}", a.my_function(), b.to_string().len(), c)]
struct MyStruct<T, U, V> {
    a: T,
    b: U,
    c: V,
}
```

**Comment by JelteF** [comment]
@tyranron 

Both proposed breaking changes sound good to me. Can you make separate issues for them so that they can be tracked in the 1.0.0 milestone? I see that 2 is already tracked in #217

Regarding suffix, one other idea that comes to mind is More (as in coming from derive_more). I don't have a strong preference to any of Custom, Smart or More (tbh all of them sound suboptimal, but I don't know a better one)

**Comment by tyranron** [comment]
@JelteF 

> Regarding suffix, one other idea that comes to mind is More (as in coming from derive_more). I don't have a strong preference to any of Custom, Smart or More (tbh all of them sound suboptimal, but I don't know a better one)

Nice idea. I do like it a lot ♥️

However, it seems that proc-macro shadowing [became allowed now](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cb2996dc27ebb499921f2ac494101abd), when we have an umbrella crate. So we can just use normal names for them:
```rust
use derive_more::Debug;

#[derive(Debug)]
struct MyStruct;
```

Still need to re-check this with tests.
