### ISSUE TITLE
More meaningful docs on docs.rs

### ISSUE THREAD

**Issue by dtolnay** [JelteF/derive_more#207]
I saw that derive_more has been doing its own thing on jeltef.github.io [since at least March 2021](https://github.com/JelteF/derive_more/commit/1e839c4f695460b4dacaa6f3b35c2cd5d792bac8), and the docs at https://docs.rs/derive_more/0.99.17 do not include any of the content from https://github.com/JelteF/derive_more/tree/v0.99.17/doc.

Since Rust 1.54 (July 2021) rustdoc knows how to include external markdown files as docs. See https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#attributes-can-invoke-function-like-macros. Could you consider whether this means the bespoke website can be dropped in favor of docs.rs at this point?

**Comment by JelteF** [comment]
I'm still waiting for this issue to be addressed: https://github.com/rust-lang/cargo/issues/739

The link you shared seems interesting, but not very useful to the problem I had: rustdoc needs some Rust item to attach the docs to, e.g. a trait. But because these are only derives, for traits that I don't own, I was unable to attach them anywhere. 

It's definitely been a 3+ years since I looked into this though. So it you know some useful trick, I'd love to know about it. I definitely would like to have the docs fully on docs.rs

**Comment by dtolnay** [comment]
> rustdoc needs some Rust item to attach the docs to

Derive macros are items. Rustdoc puts them in the rendered documentation, the only reason they're not there for derive_more is this crate has intentionally hidden them.

https://github.com/JelteF/derive_more/blob/a6eb988bc6daf5f7cbcc6aeaacdd6a964c2b6e32/src/lib.rs#L273

The way I would expect the documentation for this crate to be arranged, after that `hidden` is removed, is like this:

![Screenshot from 2022-10-09 17-29-06](https://user-images.githubusercontent.com/1940490/194786450-091408d7-739c-49de-aa4b-7e3f8a2a2ebe.png)
![Screenshot from 2022-10-09 17-29-21](https://user-images.githubusercontent.com/1940490/194786452-b045b905-1863-44ec-8a07-aea6d347c9e7.png)
