### ISSUE TITLE
Add derive(TryInto) for enums

### ISSUE THREAD

**Issue by glandium** [JelteF/derive_more#45]
I would be very interested in having TryInfo/TryFrom to convert enum variants into their underlying type.

That is:
```rust

enum Foo {
    A(usize),
    B(String),
}

impl ::std::convert::TryFrom<Foo> for usize {
    type Error = ();
    fn try_from(value: Foo) -> Result<Self, Self::Error> {
        match value {
            Foo::A(v) => Ok(v),
            _ => Err(()),
        }
    }
}

impl ::std::convert::TryFrom<Foo> for String {
    type Error = ();
    fn try_from(value: Foo) -> Result<Self, Self::Error> {
        match value {
            Foo::B(v) => Ok(v),
            _ => Err(()),
        }
    }
}
```

**Comment by glandium** [comment]
I'm giving a shot at this.

**Comment by JelteF** [comment]
Awesome. One important tip, be sure to use `cargo expand --test tryfrom.rs` to see the code that is generated when you get compile errors. Then you can copy the code into the test file (and temporarily remove the derive) and debug it that way to get much better error messages. Because if there's an error inside the implementation that you generated the rustc error message will not be very helpful.

**Comment by glandium** [comment]
I actually ended up having a problem that even `cargo expand` wasn't helpful with because the compiler would bail before expanding the proc-macro fully. I ended up using `println!` in the code.
