### ISSUE TITLE
derive From/Into &T

### ISSUE THREAD

**Issue by Geobert** [JelteF/derive_more#76]
Is there a way to generate From/Into code for &T instead of T?

**Comment by JelteF** [comment]
I just added code to master be able to do the Into derive of what you're talking about. There's now derive(IntoRef) and derive(IntoRefMut). I tried to do the same for From, but after trying a bit I think it's impossible. You can only create an &T from an &MyType(T), not the other way around. The reason is that T does not contain MyType, so you cannot take a reference to MyType. That's the way references work.

**Comment by JelteF** [comment]
Just a little update, this won't be released as `derive(IntoRef)`, but as a `derive(Into)` with an `#[into(owned, ref, ref_mut)]` attribute.

**Comment by JelteF** [comment]
This is now released as version 0.99.0. Announcement link: https://reddit.com/r/rust/comments/duptc0/derive_more_0990_released_biggest_release_ever
